# Generated by Django 3.0.8 on 2021-02-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=128)),
                ('profile_picture', models.CharField(max_length=256)),
                ('languages', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('username', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('profile_picture', models.CharField(max_length=256)),
                ('suscribed', models.BooleanField()),
                ('prev_suscriber', models.BooleanField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('header_image', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.Author')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.Comment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.Course')),
                ('fans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.Fan')),
                ('prog_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.ProgrammingLanguage')),
                ('saved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.SavedItem')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='saveditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.User'),
        ),
        migrations.AddField(
            model_name='fan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.User'),
        ),
    ]
