# Generated by Django 3.0.8 on 2021-02-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='comments',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.Comment'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.Course'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='fans',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.Fan'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='header_image',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='saved',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tutorialsApp.SavedItem'),
        ),
    ]
