# Generated by Django 3.0.8 on 2021-02-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialsApp', '0002_auto_20210218_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
