# Generated by Django 3.0.8 on 2021-02-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialsApp', '0003_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='comments',
            new_name='user_comments',
        ),
    ]
