# Generated by Django 3.0.8 on 2021-02-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialsApp', '0004_auto_20210218_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='course',
            new_name='parent_course',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='topic',
            new_name='parent_topic',
        ),
    ]
